FROM python:3.12-slim

WORKDIR /app

COPY ./pyproject.toml ./pyproject.toml
COPY ./arxiv_explorer ./arxiv_explorer
COPY ./api	./api
COPY ./tests ./tests

RUN pip install -e .[test]

CMD ["python", "tests/e2e/e2e.py", "-v"]