name: process

on:
  workflow_dispatch:
    inputs:
      versionTag:
        description: 'Version Tag'
        required: true
        default: 'v0'
  pull_request:
    branches:
      - '*'

jobs:
  run-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Verify Docker Compose installation
        run: docker-compose --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[data]"

      - name: Download Kaggle data
        run: |
          make download_data

      - name: ls data
        run: |
          ls ./input_data

      - name: Run process
        run: |
          make process_example

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_S3_BUCKET }}
          source_dir: output_data
          destination_dir: abstract_store/${{ github.event.inputs.versionTag }}
